persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type all 

listener 1883 
allow_anonymous true 

listener 8083 
protocol websockets 
allow_anonymous true

listener 8883 
allow_anonymous true 
cafile /mosquitto/config/ca.crt 
certfile /mosquitto/config/server.crt 
keyfile /mosquitto/config/server.key 
require_certificate false 

set_tcp_nodelay true
max_keepalive 60
